### PR TITLE
Adding schema and improving tests to make it p5 compatible

### PR DESCRIPTION
**Pull request by prakharjoshi**
@hvelarde  @fulv @mauritsvanrees  This is a new PR of the work done by @fulv  . 
 - This PR is to make QA and implementation differently. This includes the improvements to make this add-on compatible for p5.
 - Remove P3 dependencies.

Here travis will fail. Travis improvement will be in other branch :)

### CODE REVIEW

**Comment by hvelarde** [comment]
the idea is that tests must pass so you must fix the build to, at least, run the tests as I just done in the last commit.

**Comment by hvelarde** [comment]
the idea is that tests must pass on all supported branches before merging.

I made a few changes on the buildout configuration; update your branch with the following command before continue working on this:

```console
git reset --hard origin/add-schema-for-mail-to-group
```

**Comment by fulv** [comment]
I'm getting a strange test error, because apparently there is no `Folder` type in `portal_types`.  Any ideas?

```
> bin/test -s collective.contentrules.mailtogroup -D
Running collective.contentrules.mailtogroup.tests.test_action_mail_to_group.TestMailToGroup:Integration tests:
  Set up plone.testing.zca.LayerCleanup in 0.001 seconds.
  Set up plone.testing.z2.Startup in 0.948 seconds.
  Set up plone.app.testing.layers.PloneFixture in 24.447 seconds.
  Set up collective.contentrules.mailtogroup.tests.test_action_mail_to_group.TestMailToGroupFixture in 0.119 seconds.
  Set up collective.contentrules.mailtogroup.tests.test_action_mail_to_group.TestMailToGroup:Integration in 0.000 seconds.
  Running:
    1/6 (16.7%)

Error in test testExecute (collective.contentrules.mailtogroup.tests.test_action_mail_to_group.TestMailAction)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 399, in debug
    self.setUp()
  File "/home/fulvio/plone/ploneconfsprint/mailtogroup.plone5/eggs/plone.app.testing-5.0.2-py2.7.egg/plone/app/testing/bbb.py", line 72, in setUp
    self.afterSetUp()
  File "/home/fulvio/plone/ploneconfsprint/mailtogroup.plone5/collective/contentrules/mailtogroup/tests/test_action_mail_to_group.py", line 69, in afterSetUp
    self.portal.invokeFactory('Folder', 'target')
  File "/home/fulvio/plone/ploneconfsprint/mailtogroup.plone5/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/fulvio/plone/ploneconfsprint/mailtogroup.plone5/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 831, in constructContent
    raise ValueError('No such content type: %s' % type_name)
ValueError: No such content type: Folder

<type 'exceptions.ValueError'>:
No such content type: Folder

(Pdb) pp self.__dict__
{'Discussion Item': <FactoryTypeInformation at Discussion Item>,
 'Plone Site': <DynamicViewTypeInformation at Plone Site>,
 'TempFolder': <FactoryTypeInformation at TempFolder>,
 '__ac_local_roles__': {'admin': ['Owner']},
 '_objects': ({'id': 'Discussion Item',
               'meta_type': 'Factory-based Type Information'},
              {'id': 'Plone Site',
               'meta_type': 'Factory-based Type Information with dynamic views'},
              {'id': 'TempFolder',
               'meta_type': 'Factory-based Type Information'}),
 'title': 'Controls the available content types in your portal'}
```

**Comment by davisagli** [comment]
@fulv plone.app.testing.PLONE_FIXTURE does not include content types. It's used as the basis for both plone.app.contenttypes- and ATContentTypes-based fixtures.

**Comment by hvelarde** [comment]
@fulv I think this package is mature and I'm fine with making a new 2.0 release oncly compatible with Plone 5 and beyond.

feel free to remove the conditionals and unneeded code.

**Comment by fulv** [comment]
Woot!  All tests pass, 4.3, 5.0 and 5.1!
Ready to merge, but do not release yet.
There is one more issue that needs to be fixed.

**Comment by fulv** [comment]
Now with squashed commits.

**Comment by fulv** [comment]
@hvelarde Would you do me the honor of merging this?

**Pull request merged**
