### PR TITLE
Another attempt to resolve six=1.10.0 version conflict.

### PR DESCRIPTION
**Pull request by fulv**

### CODE REVIEW

**Comment by ida** [comment]
That looks good! I'll add that to the other PR, to see if tests will pass, then.

**Comment by ida** [comment]
I see you've dine that already but's still breaking. That's funny, if there's no difference between the branches but a changed README. Now looking if someone else has the same error...
Thanks for continuing to find a solution! (@fulv)

**Comment by fulv** [comment]
@ida I have no idea why, but it seems like travis was always restarting the tests from your first commit, instead of the latest.  As a consequence, we don't know whether any of the intermediate commits actually fixed the problem or not.
Anyway, merging now.

**Comment by ida** [comment]
@fulv Lost this out of sight, if you find some time for a release, that'll be süper.

**Comment by fulv** [comment]
I don't have time right now, I've scheduled it for myself for after Sep 10.

**Comment by ida** [comment]
Oh cool, thanks. Have a good time!

**Comment by ida** [comment]
@fulv If you don't find time, can you please regain ownership to my user ('ida'), so I can do it myself? Thanks!

**Comment by ida** [comment]
@fulv Can't find our latest convo, but I see now you've been so kind to change the README and make a release, huuuuge thanks for that! And have a great day!

**Pull request merged**
